spring.application.name=CRUD_SPRING
# URL de conexion a la base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/crud
# Nombre de usuario para la base de datos
spring.datasource.username=postgres
# Contrasena para la base de datos
spring.datasource.password=1234
# Controlador para PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver
# Configuracion de Hibernate para actualizar el esquema de la base de datos
spring.jpa.hibernate.ddl-auto=update
# Muestra las consultas SQL ejecutadas
spring.jpa.show-sql=true
# Puerto del Servidor
server.port=8080